### PR TITLE
Add ability to provide license file via yaml

### PR DESCRIPTION
**Pull request by DimmKirr**
This PR is adding ability to specify your offline license file as yaml data structure right in role parameters.

I followed the pattern of separate config files for different node type, so there are 2 different license file names for data and meta nodes.

### CODE REVIEW

**Comment by DimmKirr** [comment]
bump

**Comment by DimmKirr** [comment]
Can this be merged please?

**Comment by pmyjavec** [comment]
@kireevco, I'm sorry about this! I didn't see any notifications and only just realised this PR existed. Thank you for the contribution and I'll take a look at my notification settings now.

**Comment by pmyjavec** [comment]
@kireevco, by the way, there were a couple of minor issues when using your new license file changes, I had to make a few minor adjustments. But again, thanks for your contribution.

Please take a look at them in 327d2528fa39cf89550e4322068c1fe00eb988dc, I hope these changes are ok for you too.

**Comment by pmyjavec** [comment]
Sorry @kireevco, also be84e1d532b9d82bc3de1ac8ef3fd579e9124745

**Pull request merged**
